### ISSUE TITLE
no model 

### ISSUE THREAD

**Issue by SunshineDou** [rhvonlehe/OpenGLExamples#1]
Hello, I have run the OpenGLDemo, but the result is as follows, there is no model in the interface, What's the matter?

![2019-01-22 16-39-20](https://user-images.githubusercontent.com/25578572/51522434-4f72d780-1e64-11e9-95fb-e293431ef79a.png)
Thank you very much

**Comment by rhvonlehe** [comment]
There should be a menu bar with a single 'File' drop-down menu near the top left.  I haven't tried this on Linux myself, and it looks like that's what you're using.  Let me try that.

**Comment by rhvonlehe** [comment]
Just tried on Linux and not having much luck.  The gradient in the background isn't there.  The file menu also doesn't work.  It shows up, but no members.  The same code works fine under Windows.

**Comment by rhvonlehe** [comment]
In any case, this is what I see on Windows after loading the included Monkey and Teeth:
![image](https://user-images.githubusercontent.com/6163831/51582828-7f859f00-1e93-11e9-968e-df4f8a3d2eb9.png)

**Comment by SunshineDou** [comment]
@rhvonlehe Thank you very much for your replying.
As I am researching on the ply model reader and virtual camera to achieve roaming in 3D ply model, I find your code maybe useful to me. I have tried on windows these days.  the result is as follows:
![1](https://user-images.githubusercontent.com/25578572/52521321-6876e780-2cb0-11e9-8673-4d7f4aceb6de.PNG)
the monkey model is really small and the teeth model is very huge. and in the meantime when I click on the left six button"front, back, left, right, top, button", there is no change, What's the matter? could you please give me a help?
Thank you very much sincerely

**Comment by rhvonlehe** [comment]
I apologize, my documentation is not great.  I tend to use Github as a way for me to save off things I've worked on that others might be interested in, but I haven't spent any time documenting.  To adjust the size of the model on the screen use alt-middle mouse button.  

You can also swap between perspective and orthonormal views by hitting the 'p' and 'o' keys.

**Comment by rhvonlehe** [comment]
As this was a demo program for me to try out different Qt and OpenGL features, I acknowledge it is very incomplete.  For example, the view buttons on the left only work for the monkey view, not the teeth.

If you wanted the buttons to operate on both, you could add connect calls at the bottom of the MainWindow constructor.

**Comment by SunshineDou** [comment]
@rhvonlehe Thank you very much sincerely, I will have a try
